language: node_js
sudo: false
dist: trusty

node_js:
  - node

cache:
  yarn: true
  directories:
    - "node_modules"

script:
  - yarn lint
  - yarn test
  - yarn benchmark

before_deploy:
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci
  local_dir: ./build
  fqdn: solver.0xcaff.me
