language: node_js
sudo: false
dist: trusty

addons:
  apt:
    packages:
      # Dependencies Needed for Canvas https://github.com/Automattic/node-canvas
      - libcairo2-dev
      - libjpeg8-dev
      - libpango1.0-dev
      - libgif-dev
      - build-essential
      - g++

node_js:
  - node

cache:
  yarn: true
  directories:
    - "node_modules"

script:
  - yarn lint
  - yarn test
  - yarn benchmark

before_deploy:
  - yarn build
  - ln -s build/index.html build/200.html

deploy:
  provider: surge
  skip_cleanup: true
  project: ./build
  domain: solver.0xcaff.me
