version: 2
jobs:
  test:
    docker:
      - image: node:14

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-

      - run:
          name: Install Deps
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Test
          command: yarn test

      - run:
          name: Check Formatting
          command: yarn check-formatting

      - run:
          name: Build
          command: yarn build

      - run:
          name: Analyze Bundle
          command: yarn analyze -- --html bundle-explorer.html

      - store_artifacts:
          path: bundle-explorer.html

  deploy:
    docker:
      - image: node:14

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-

      - run:
          name: Install Deps
          command: yarn install

      - run:
          name: Build
          command: yarn build

      - run:
          name: Copy Index File
          command: cp build/index.html build/200.html

      - run:
          name: Deploy to Surge
          command: yarn surge --project ./build --domain solver.0xcaff.me

  update_data:
    docker:
      - image: node:14

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-

      - run:
          name: Install Deps
          command: yarn install

      - run:
          name: Install Cloud SQL Proxy
          command: wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy && chmod +x cloud_sql_proxy

      - run:
          name: Write Service Key To File
          command: echo $GCLOUD_SERVICE_KEY > service-key.json

      - run:
          name: Run Cloud SQL Proxy
          command: ./cloud_sql_proxy -credential_file=service-key.json -instances=wordsearch-172001:us-central1:analytics-1=tcp:5432
          background: true

      - run:
          name: Update Data
          environment:
            PGUSER: 'analytics'
            PGDATABASE: 'analytics'
          command: yarn update-data

workflows:
  version: 2
  test:
    jobs:
      - test
      - hold:
          type: approval
          requires:
           - test
          filters:
            branches:
              only: master

      - deploy:
          requires:
            - hold

  update_data:
    jobs:
      - update_data

