version: 2
jobs:
  test:
    docker:
      - image: node:10

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-

      - run:
          name: Install Deps
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Test
          command: yarn test

      - run:
          name: Check Formatting
          command: yarn check-formatting

      - run:
          name: Build
          command: yarn build

  deploy:
    docker:
      - image: node:10

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-

      - run:
          name: Install Deps
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Build
          command: yarn build

      - run:
          name: Copy Index File
          command: cp build/index.html build/200.html

      - run:
          name: Deploy to Surge
          command: yarn surge --project ./build --domain solver.0xcaff.me

workflows:
  version: 2
  test:
    jobs:
      - test
      - hold:
          type: approval
          requires:
           - test
          filters:
            branches:
              only: master

      - deploy:
          requires:
            - hold
